// NB: This file is auto-generated by 'TokenKind.cs_code_generator.ps1'. Your changes here will be overwritten.

using System.Management.Automation.Language;

namespace ExplainPowershell.SyntaxAnalyzer
{
    public static partial class Helpers {
        public static (string, string) TokenExplainer(TokenKind tokenKind)
        {
            var description = string.Empty;
            var helpQuery = string.Empty;

            switch (tokenKind)
            {
                case TokenKind.Ampersand:
                    description = "The invocation operator '&'.";
                    helpQuery = "about_Operators";
                    break;
                case TokenKind.And:
                    description = "The logical and operator '-and'.";
                    helpQuery = "about_Logical_Operators";
                    break;
                case TokenKind.AndAnd:
                    description = "The (unimplemented) operator '&&'.";
                    helpQuery = "";
                    break;
                case TokenKind.As:
                    description = "The type conversion operator '-as'.";
                    helpQuery = "about_Type_Operators";
                    break;
                case TokenKind.Assembly:
                    description = "The 'assembly' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.AtCurly:
                    description = "The opening token of a hash expression '@{'.";
                    helpQuery = "about_Hash_Tables";
                    break;
                case TokenKind.AtParen:
                    description = "The opening token of an array expression '@('.";
                    helpQuery = "about_Operators";
                    break;
                case TokenKind.Band:
                    description = "The bitwise and operator '-band'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.Base:
                    description = "The 'base' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Begin:
                    description = "The 'begin' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Bnot:
                    description = "The bitwise not operator '-bnot'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.Bor:
                    description = "The bitwise or operator '-bor'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.Break:
                    description = "The 'break' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Bxor:
                    description = "The bitwise exclusive or operator '-xor'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.Catch:
                    description = "The 'catch' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Ccontains:
                    description = "The case sensitive contains operator '-ccontains'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Ceq:
                    description = "The case sensitive equal operator '-ceq'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cge:
                    description = "The case sensitive greater than or equal operator '-cge'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cgt:
                    description = "The case sensitive greater than operator '-cgt'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cin:
                    description = "The case sensitive in operator '-cin'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Class:
                    description = "The 'class' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Cle:
                    description = "The case sensitive less than or equal operator '-cle'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Clike:
                    description = "The case sensitive like operator '-clike'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Clt:
                    description = "The case sensitive less than operator '-clt'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cmatch:
                    description = "The case sensitive match operator '-cmatch'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cne:
                    description = "The case sensitive not equal operator '-cne'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cnotcontains:
                    description = "The case sensitive not contains operator '-cnotcontains'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cnotin:
                    description = "The case sensitive not in operator '-notin'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cnotlike:
                    description = "The case sensitive notlike operator '-cnotlike'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Cnotmatch:
                    description = "The case sensitive not match operator '-cnotmatch'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Colon:
                    description = "The PS class base class and implemented interfaces operator ':'. Also used in base class ctor calls.";
                    helpQuery = "";
                    break;
                case TokenKind.ColonColon:
                    description = "The static member access operator '::'.";
                    helpQuery = "";
                    break;
                case TokenKind.Comma:
                    description = "The unary or binary array operator ','.";
                    helpQuery = "";
                    break;
                case TokenKind.Command:
                    description = "The 'command' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Comment:
                    description = "A single line comment, or a delimited comment.";
                    helpQuery = "";
                    break;
                case TokenKind.Configuration:
                    description = "The 'configuration' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Continue:
                    description = "The 'continue' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Creplace:
                    description = "The case sensitive replace operator '-creplace'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Csplit:
                    description = "The case sensitive split operator '-csplit'.";
                    helpQuery = "about_Split";
                    break;
                case TokenKind.Data:
                    description = "The 'data' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Define:
                    description = "The (unimplemented) 'define' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Divide:
                    description = "The division operator '/'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.DivideEquals:
                    description = "The division assignment operator '/='.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.Do:
                    description = "The 'do' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.DollarParen:
                    description = "The opening token of a sub-expression '$('.";
                    helpQuery = "about_Operators";
                    break;
                case TokenKind.Dot:
                    description = "The instance member access or dot source invocation operator '.'.";
                    helpQuery = "about_Operators";
                    break;
                case TokenKind.DotDot:
                    description = "The range operator '..'.";
                    helpQuery = "about_Operators";
                    break;
                case TokenKind.DynamicKeyword:
                    description = "The token kind for dynamic keywords";
                    helpQuery = "";
                    break;
                case TokenKind.Dynamicparam:
                    description = "The 'dynamicparam' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Else:
                    description = "The 'else' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.ElseIf:
                    description = "The 'elseif' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.End:
                    description = "The 'end' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.EndOfInput:
                    description = "Marks the end of the input script or file.";
                    helpQuery = "";
                    break;
                case TokenKind.Enum:
                    description = "The 'enum' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Equals:
                    description = "The assignment operator '='.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.Exclaim:
                    description = "The logical not operator '!'.";
                    helpQuery = "about_Logical_Operators";
                    break;
                case TokenKind.Exit:
                    description = "The 'exit' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Filter:
                    description = "The 'filter' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Finally:
                    description = "The 'finally' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.For:
                    description = "The 'for' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Foreach:
                    description = "The 'foreach' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Format:
                    description = "The string format operator '-f'.";
                    helpQuery = "about_Operators";
                    break;
                case TokenKind.From:
                    description = "The (unimplemented) 'from' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Function:
                    description = "The 'function' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Generic:
                    description = "A token that is only valid as a command name, command argument, function name, or configuration name. It may contain characters not allowed in identifiers. Tokens with this kind are always instances of StringLiteralToken or StringExpandableToken if the token contains variable references or subexpressions.";
                    helpQuery = "";
                    break;
                case TokenKind.HereStringExpandable:
                    description = "A double quoted here string literal. Tokens with this kind are always instances of StringExpandableToken. even if there are no nested tokens to expand.";
                    helpQuery = "";
                    break;
                case TokenKind.HereStringLiteral:
                    description = "A single quoted here string literal. Tokens with this kind are always instances of StringLiteralToken.";
                    helpQuery = "";
                    break;
                case TokenKind.Hidden:
                    description = "The 'hidden' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Icontains:
                    description = "The case insensitive contains operator '-icontains' or '-contains'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Identifier:
                    description = "A simple identifier, always begins with a letter or '', and is followed by letters, numbers, or ''.";
                    helpQuery = "";
                    break;
                case TokenKind.Ieq:
                    description = "The case insensitive equal operator '-ieq' or '-eq'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.If:
                    description = "The 'if' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Ige:
                    description = "The case insensitive greater than or equal operator '-ige' or '-ge'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Igt:
                    description = "The case insensitive greater than operator '-igt' or '-gt'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Iin:
                    description = "The case insensitive in operator '-iin' or '-in'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Ile:
                    description = "The case insensitive less than or equal operator '-ile' or '-le'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Ilike:
                    description = "The case insensitive like operator '-ilike' or '-like'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Ilt:
                    description = "The case insensitive less than operator '-ilt' or '-lt'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Imatch:
                    description = "The case insensitive match operator '-imatch' or '-match'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.In:
                    description = "The 'in' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Ine:
                    description = "The case insensitive not equal operator '-ine' or '-ne'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.InlineScript:
                    description = "The 'InlineScript' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Inotcontains:
                    description = "The case insensitive notcontains operator '-inotcontains' or '-notcontains'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Inotin:
                    description = "The case insensitive notin operator '-inotin' or '-notin'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Inotlike:
                    description = "The case insensitive not like operator '-inotlike' or '-notlike'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Inotmatch:
                    description = "The case insensitive not match operator '-inotmatch' or '-notmatch'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Interface:
                    description = "The 'interface' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Ireplace:
                    description = "The case insensitive replace operator '-ireplace' or '-replace'.";
                    helpQuery = "about_comparison_operators";
                    break;
                case TokenKind.Is:
                    description = "The type test operator '-is'.";
                    helpQuery = "about_Type_Operators";
                    break;
                case TokenKind.IsNot:
                    description = "The type test operator '-isnot'.";
                    helpQuery = "about_Type_Operators";
                    break;
                case TokenKind.Isplit:
                    description = "The case insensitive split operator '-isplit' or '-split'.";
                    helpQuery = "about_Split";
                    break;
                case TokenKind.Join:
                    description = "The join operator '-join'.";
                    helpQuery = "about_Join";
                    break;
                case TokenKind.Label:
                    description = "A label token - always begins with ':', followed by the label name. Tokens with this kind are always instances of LabelToken.";
                    helpQuery = "";
                    break;
                case TokenKind.LBracket:
                    description = "The opening square brace token '['.";
                    helpQuery = "";
                    break;
                case TokenKind.LCurly:
                    description = "The opening curly brace token '{'.";
                    helpQuery = "";
                    break;
                case TokenKind.LineContinuation:
                    description = "A line continuation (backtick followed by newline).";
                    helpQuery = "";
                    break;
                case TokenKind.LParen:
                    description = "The opening parenthesis token '('.";
                    helpQuery = "";
                    break;
                case TokenKind.Minus:
                    description = "The substraction operator '-'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.MinusEquals:
                    description = "The subtraction assignment operator '-='.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.MinusMinus:
                    description = "The pre-decrement operator '--'.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.Module:
                    description = "The 'module' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Multiply:
                    description = "The multiplication operator '*'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.MultiplyEquals:
                    description = "The multiplcation assignment operator '*='.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.Namespace:
                    description = "The 'namespace' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.NewLine:
                    description = "A newline (one of '\n', '\r', or '\r\n').";
                    helpQuery = "";
                    break;
                case TokenKind.Not:
                    description = "The logical not operator '-not'.";
                    helpQuery = "about_Logical_Operators";
                    break;
                case TokenKind.Number:
                    description = "Any numerical literal token. Tokens with this kind are always instances of NumberToken.";
                    helpQuery = "";
                    break;
                case TokenKind.Or:
                    description = "The logical or operator '-or'.";
                    helpQuery = "about_Logical_Operators";
                    break;
                case TokenKind.OrOr:
                    description = "The (unimplemented) operator '||'.";
                    helpQuery = "";
                    break;
                case TokenKind.Parallel:
                    description = "The 'parallel' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Param:
                    description = "The 'param' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Parameter:
                    description = "A parameter to a command, always begins with a dash ('-'), followed by the parameter name. Tokens with this kind are always instances of ParameterToken.";
                    helpQuery = "";
                    break;
                case TokenKind.Pipe:
                    description = "The pipe operator '|'.";
                    helpQuery = "about_pipelines";
                    break;
                case TokenKind.Plus:
                    description = "The addition operator '+'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.PlusEquals:
                    description = "The addition assignment operator '+='.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.PlusPlus:
                    description = "The pre-increment operator '++'.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.PostfixMinusMinus:
                    description = "The post-decrement operator '--'.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.PostfixPlusPlus:
                    description = "The post-increment operator '++'.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.Private:
                    description = "The 'private' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Process:
                    description = "The 'process' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Public:
                    description = "The 'public' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.QuestionDot:
                    description = "";
                    helpQuery = "";
                    break;
                case TokenKind.QuestionLBracket:
                    description = "";
                    helpQuery = "";
                    break;
                case TokenKind.QuestionMark:
                    description = "";
                    helpQuery = "";
                    break;
                case TokenKind.QuestionQuestion:
                    description = "";
                    helpQuery = "";
                    break;
                case TokenKind.QuestionQuestionEquals:
                    description = "";
                    helpQuery = "";
                    break;
                case TokenKind.RBracket:
                    description = "The closing square brace token ']'.";
                    helpQuery = "";
                    break;
                case TokenKind.RCurly:
                    description = "The closing curly brace token '}'.";
                    helpQuery = "";
                    break;
                case TokenKind.RedirectInStd:
                    description = "The (unimplemented) stdin redirection operator '<'.";
                    helpQuery = "about_Redirection";
                    break;
                case TokenKind.Redirection:
                    description = "A redirection operator such as '2>&1' or '>>'.";
                    helpQuery = "about_Redirection";
                    break;
                case TokenKind.Rem:
                    description = "The modulo division (remainder) operator '%'.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.RemainderEquals:
                    description = "The modulo division (remainder) assignment operator '%='.";
                    helpQuery = "about_assignment_operators";
                    break;
                case TokenKind.Return:
                    description = "The 'return' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.RParen:
                    description = "The closing parenthesis token ')'.";
                    helpQuery = "";
                    break;
                case TokenKind.Semi:
                    description = "The statement terminator ';' (semicolon).";
                    helpQuery = "";
                    break;
                case TokenKind.Sequence:
                    description = "The 'sequence' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Shl:
                    description = "The shift left operator.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.Shr:
                    description = "The shift right operator.";
                    helpQuery = "about_arithmetic_operators";
                    break;
                case TokenKind.SplattedVariable:
                    description = "A splatted variable token, always begins with '@' and followed by the variable name. Tokens with this kind are always instances of VariableToken.";
                    helpQuery = "";
                    break;
                case TokenKind.Static:
                    description = "The 'static' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.StringExpandable:
                    description = "A double quoted string literal. Tokens with this kind are always instances of StringExpandableToken even if there are no nested tokens to expand.";
                    helpQuery = "";
                    break;
                case TokenKind.StringLiteral:
                    description = "A single quoted string literal. Tokens with this kind are always instances of StringLiteralToken.";
                    helpQuery = "";
                    break;
                case TokenKind.Switch:
                    description = "The 'switch' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Throw:
                    description = "The 'throw' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Trap:
                    description = "The 'trap' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Try:
                    description = "The 'try' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Type:
                    description = "The 'type' keyword";
                    helpQuery = "";
                    break;
                case TokenKind.Unknown:
                    description = "An unknown token, signifies an error condition.";
                    helpQuery = "";
                    break;
                case TokenKind.Until:
                    description = "The 'until' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Using:
                    description = "The (unimplemented) 'using' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Var:
                    description = "The (unimplemented) 'var' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Variable:
                    description = "A variable token, always begins with '$' and followed by the variable name, possibly enclose in curly braces. Tokens with this kind are always instances of VariableToken.";
                    helpQuery = "";
                    break;
                case TokenKind.While:
                    description = "The 'while' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Workflow:
                    description = "The 'workflow' keyword.";
                    helpQuery = "";
                    break;
                case TokenKind.Xor:
                    description = "The logical exclusive or operator '-xor'.";
                    helpQuery = "about_Logical_Operators";
                    break;
            }
            return (description, helpQuery);
        }
    }
}
