# This github actions pipeline is intended to do a basic resource deployment in an Azure resoucegroup, it does not set up App Insights. 
#
# Usage: 
#   - Create a resource group in Azure, with the name 'explainpowershelltest', or a different name -> make sure to change the `RESOURCE_GROUP_NAME` environment variable accordingly.
#   - Create a Service Principal in Azure with permissions to deploy to this resource group: 
#        `az ad sp create-for-rbac --name explainpowershell --role contributor --scopes /subscriptions/{YourSubscriptionId}/resourceGroups/explainpowershelltest --sdk-aut`
#   - Add the json output of the previous command as a new secret in GitHub, with the name `AZURE_SERVICE_PRINCIPAL`.
# Read full documentation with examples here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-github-actions

name: Deploy_Azure_Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP_NAME: explainpowershelltest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./explainpowershell.azureinfra/template.json
          parameters: ./explainpowershell.azureinfra/parameters.json
          deploymentMode: incremental