# This github actions pipeline is intended to write help data to the Azure Table storage database. 
#

name: Fill_Help_Database

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: test func
        shell: pwsh
        run: |
          write-Output "start"
          write-Output ${{ secret.TEST }}
          write-Output "done"