# This github actions pipeline is intended to write help data to the Azure Table storage database. 
#

name: Fill_Help_Database

on:
  push:
    branches: [test_secret]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TEST }}