# This github actions pipeline is intended to write help data to the Azure Table storage database. 
#

name: Fill_Help_Database

on:
  push:
    branch: [func_testing]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: explainpowershellsyntaxanalyzertest
  AZURE_SUBSCRIPTION_ID: ced1b96d-9473-4313-b1c2-f8b30db08841
  RESOURCE_GROUP_NAME: explainpowershelltest
  BLOB_STORAGE_ACCOUNT_NAME: explainpowershelltest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: install azure functions core tools
        shell: bash
        run: |
          sudo apt-get update
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y install --no-install-recommends apt-utils dialog 2>&1
          sudo apt-get -y install git openssh-client less unzip iproute2 procps curl apt-transport-https gnupg2 lsb-release
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor >microsoft.asc.gpg
          sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
          wget -q https://packages.microsoft.com/config/debian/9/prod.list
          sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
          sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
          sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get -y install azure-cli azure-functions-core-tools-3
          sudo apt-get autoremove -y
          sudo apt-get clean -y
          sudo rm -rf /var/lib/apt/lists/*

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TEST }}

      - name: set app settings
        shell: pwsh
        run: |
          set-location ./explainpowershell.analysisservice
          az account set --subscription ${{ env.AZURE_SUBSCRIPTION_ID }}
          func azure storage fetch-connection-string ${{ env.BLOB_STORAGE_ACCOUNT_NAME }}
          $connectionstring = (Get-Content ./local.settings.json | ConvertFrom-Json ).Values.${{ env.AZURE_FUNCTIONAPP_NAME }}_STORAGE
          az functionapp config appsettings set --settings "AzureWebJobsStorage=$connectionstring" --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
          az functionapp config appsettings set --settings "FUNCTIONS_WORKER_RUNTIME=dotnet" --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
          az functionapp config appsettings set --settings "FUNCTIONS_EXTENSION_VERSION=~3" --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}

      - name: test func
        shell: pwsh
        run: |
          set-location ./explainpowershell.analysisservice
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --force