# This github actions pipeline is intended to write help data to the Azure Table storage database. 
#

name: Fill_Help_Database

on: 
  push:
    branch: [ func_testing ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install azure functions core tools
        shell: bash
        run: | 
          sudo apt-get update 
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y install --no-install-recommends apt-utils dialog 2>&1 
          sudo apt-get -y install git openssh-client less unzip iproute2 procps curl apt-transport-https gnupg2 lsb-release 
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor >microsoft.asc.gpg 
          sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ 
          wget -q https://packages.microsoft.com/config/debian/9/prod.list 
          sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list 
          sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg 
          sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list 
          sudo echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" >/etc/apt/sources.list.d/azure-cli.list 
          sudo apt-get update 
          sudo apt-get -y install azure-cli azure-functions-core-tools-3 
          sudo apt-get autoremove -y 
          sudo apt-get clean -y 
          sudo rm -rf /var/lib/apt/lists/*

      - name: test func
        shell: pwsh 
        run: |
          set-location ./explainpowershell.analysisservice
          func host start