# This github actions pipeline is intended to write help data to the Azure Table storage database. 
#

name: Fill_Help_Database

on: 
  workflow_dispatch:

steps:
  - name: test func
    shell: pwsh 
    run: |
      set-location ./explainpowershell.analysisservice
      func host start