name: test

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  buildFrontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v1

    - name: update-help
      shell: pwsh
      run: |
        gci '~/.local/share/powershell/Help/
        update-help -force
        gci '~/.local/share/powershell/Help/